# -*- coding: utf-8 -*-
"""
Created on Mon Apr  9 19:00:48 2018

@author: Adebraine
"""

"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

import numpy as np

x = 1
y = 2
run = True
result = []

while run:
    xold = y
    y = x + y
    x = xold
    
    if xold % 2 == 0:
        result.append(xold)
    
    
    if y >= 4000000:
        run = False

print(np.sum(result))